### PR TITLE
Fix missing MethodNotAllowed in Router interface

### PR DESCRIPTION
**Pull request by jiop**

### CODE REVIEW

**Comment by pkieltyka** [comment]
@jiop thanks for this, but a part of me would rather keep Router small, even though the Mux has a few extra methods that are available to it. In that case, one could assert to a *Mux to use it, and in actuality, chi.NewRouter() returns a *Mux. Let me know what you think.

**Comment by jiop** [comment]
@pkieltyka My main concern is about consistency. NotFound handler is available in the Router interface so I thought that MethodNotAllowed should be there as well.

**Comment by pkieltyka** [comment]
@jiop yea I agree with that rationale. I felt MethodNotAllowed won't be used as commonly as NotFound, so thats why I kept it a little bit lower level. I'll leave this PR open and see what other contributors think too.

**Comment by jiop** [comment]
Hi @pkieltyka, any updates on this PR?

**Comment by pkieltyka** [comment]
Hey Jeremie, I'm going to hold off and close it for now.

**Pull request merged**
