### PR TITLE
Makes Parameters respect encoded URI components.

### PR DESCRIPTION
**Pull request by eemeyer**
Resolves https://github.com/pressly/chi/issues/148

### CODE REVIEW

**Comment by pkieltyka** [comment]
thanks for this PR, I will review it for correctness and performance soon

**Comment by eemeyer** [comment]
Do you have a timeline for incorporating this patch? I've got a project that currently depends on my fork of `chi`, and I'd rather reference this repository's official version.

**Comment by pkieltyka** [comment]
Hey Eric, I'm just in a short vacation but I'll be back on Sunday and review this PR / merge or otherwise next week! Cheers. Thanks for waiting.

**Comment by eemeyer** [comment]
Perfect. Thanks for the update. Enjoy your vacation!

**Comment by pkieltyka** [comment]
hey @eemeyer - after some benchmarks and thought, I've settled on 822e7b85e22b3f7a573782c3674edf8e732fb427 which resolves your issue, but you will have to unescape the value in the url param in your handlers. Thanks for the PR!

**Comment by eemeyer** [comment]
Thanks! Your solution makes good sense. I didn't see a good way to know whether the url path component needed unescaping in `findPath`, and agree that always unescaping the path was not the correct solution.

**Pull request closed without merging**
