### PR TITLE
Unused params, unused code and test on 1.8.x

### PR DESCRIPTION
**Pull request by mvdan**

### CODE REVIEW

**Comment by mvdan** [comment]
Actually, fuck, made one mistake.

**Comment by mvdan** [comment]
The duplicate node parameter wasn't unused - in the recursive call, it's a different value compared to the receiver parameter.

Reverted that bit.

**Comment by mvdan** [comment]
Also, no Travis?

**Comment by pkieltyka** [comment]
thanks for the PR - but what is the value here? I'd like to keep ntRegexp because I want someone to implement it one day.

**Comment by mvdan** [comment]
Sure, I'll undo that.

**Comment by mvdan** [comment]
@pkieltyka done, FYI

**Comment by pkieltyka** [comment]
I'm going to hold off on this PR at the moment, it doesn't really change anything for now. Feel free to take some time at https://github.com/pressly/chi/issues/167 though :)

**Comment by mvdan** [comment]
Bump? I can get that there's no hurry, but this is a bit extreme.

**Comment by mvdan** [comment]
Is this repo in some sort of freeze? If so, could you document it? I'm still confused as to what is going on with contributions to this repo, as the repo is active.

**Comment by VojtechVitek** [comment]
@mvdan This Pull Request is low priority, since it doesn't really change chi functionality. Please, be patient.

**Comment by pkieltyka** [comment]
hey @mvdan whats the rush with this specific PR? it literally changes nothing

**Comment by mvdan** [comment]
Perhaps I'm being impatient - apologies. I just don't understand why it's being parked. I keep an eye on pull requests that I send, and I worry about old ones because they tend to mean extra work like remembering what changes I made or why, and fixing conflicts.

If the repo is in some sort of freeze or prioritization for v3, I'd understand. My point above is that I haven't seen that written anywhere.

**Comment by pkieltyka** [comment]
@mvdan I am very picky about changes to the chi project to uphold a very high code quality requirement and design. As well, I take a lot of consideration present and future to any PR or suggestion to the project - which can take time. Welcome to open source dev :)

**Pull request closed without merging**
